'use client';

import { useEffect, useState } from 'react';

export default function StickyTOC() {
  const [headings, setHeadings] = useState<{ id: string; text: string }[]>([]);
  const [activeId, setActiveId] = useState<string>('');

  useEffect(() => {
    // Collect all H2s inside the article prose area
    const article = document.querySelector('.prose');
    if (!article) return;

    const h2s = article.querySelectorAll('h2');
    const items = Array.from(h2s)
      .filter((h) => h.id) // only those with an id (auto-generated by MDX)
      .map((h) => ({ id: h.id, text: h.textContent ?? '' }));
    setHeadings(items);

    // IntersectionObserver to track current section
    const observer = new IntersectionObserver(
      (entries) => {
        // Find the first heading that's intersecting (visible)
        for (const entry of entries) {
          if (entry.isIntersecting) {
            setActiveId(entry.target.id);
            break;
          }
        }
      },
      {
        rootMargin: '-80px 0px -60% 0px',
        threshold: 0,
      }
    );

    h2s.forEach((h) => {
      if (h.id) observer.observe(h);
    });

    return () => observer.disconnect();
  }, []);

  if (headings.length === 0) return null;

  return (
    <nav aria-label="Table of contents" className="text-sm">
      <p className="font-semibold text-gray-900 text-xs uppercase tracking-wider mb-3">
        Contents
      </p>
      <ul className="space-y-1 border-l-2 border-gray-200">
        {headings.map((h) => {
          const isActive = h.id === activeId;
          return (
            <li key={h.id}>
              <a
                href={`#${h.id}`}
                className={`block pl-3 py-1 text-[13px] leading-snug transition-colors duration-150 border-l-2 -ml-[2px] ${
                  isActive
                    ? 'border-blue-600 text-blue-600 font-medium'
                    : 'border-transparent text-gray-500 hover:text-gray-800 hover:border-gray-400'
                }`}
              >
                {h.text}
              </a>
            </li>
          );
        })}
      </ul>
    </nav>
  );
}
